name: Update Live Site

on:
  push:
    branches: [ master ]

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST https://yarc.world/cgi/buildsite.sh
